
lavalink:
  plugins:
  - dependency: com.github.TopiSenpai.LavaSrc:lavasrc-plugin:85b39d1
    repository: https://maven.topi.wtf/snapshots
  - dependency: com.dunctebot:skybot-lavalink-plugin:1.4.1
    repository: https://m2.duncte123.dev/releases
  - dependency: com.github.topisenpai:sponsorblock-plugin:2.0.0
    repository: https://jitpack.io
  - dependency: me.rohank05:lavalink-filter-plugin:0.0.1
    repository: https://jitpack.io
  - dependency: com.github.esmBot:lava-xm-plugin:v0.2.1
    repository: https://jitpack.io
  server:
    bufferDurationMs: 400
    filters:
      channelMix: true
      distortion: true
      echo: true
      equalizer: true
      karaoke: true
      lowPass: true
      rotation: true
      timescale: true
      tremolo: true
      vibrato: true
      volume: true
    frameBufferDurationMs: 1000
    gc-warnings: true
    opusEncodingQuality: 10
    password: youshallnotpass
    playerUpdateInterval: 30
    resamplingQuality: HIGH
    soundcloudSearchEnabled: true
    sources:
      bandcamp: true
      http: true
      local: true
      soundcloud: true
      twitch: true
      vimeo: true
      youtube: true
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    youtubePlaylistLoadLimit: 100
    youtubeSearchEnabled: true
logging:
  file:
    path: ./logs/
  level:
    lavalink: INFO
    root: INFO
  logback:
    rollingpolicy:
      max-file-size: 25MB
      max-history: 7
      total-size-cap: 1GB
  request:
    enabled: true
    includeClientInfo: true
    includeHeaders: false
    includePayload: true
    includeQueryString: true
    maxPayloadLength: 10000
metrics:
  prometheus:
    enabled: false
    endpoint: /metrics
plugins:
  dunctebot:
    sources:
      clypit: true
      getyarn: true
      mixcloud: true
      ocremix: true
      pornhub: true
      reddit: true
      soundgasm: true
      tiktok: true
      tts: true
    ttsLanguage: en-US
  lavasrc:
    providers:
    - dzisrc:%ISRC%
    - ytmsearch:"%ISRC%"
    - ytsearch:"%ISRC%"
    - ytmsearch:%QUERY%
    - ytsearch:%QUERY%
    - dzsearch:%QUERY%
    - scsearch:%QUERY%
    sources:
      applemusic: true
      deezer: false # change to true if you have a deezer token below
      spotify: false # change to true if you have a spotify token below
      yandexmusic: false
    applemusic:
      countryCode: US
#    deezer:
#      masterDecryptionKey: CHANGE_ME
#    spotify:
#      clientId: CHANGE_ME
#      clientSecret: CHANGE_ME
#      countryCode: US
server:
  address: 0.0.0.0
  port: 2155
